services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: pact
      POSTGRES_USER: pact
      POSTGRES_DB: pact
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
